id: AB1B8DCF8
base_file: f1F24.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:15:54.421155
  last_modified_at: 2022-05-30 18:15:54.421161
