id: AB1B8DCF8
base_file: fD46A.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:15:54.423941
  last_modified_at: 2022-05-30 18:15:54.423944
